[assembly: EPIC.CameraInterface.RootNamespaceAttribute("EPIC.CameraInterface")]
[assembly: System.Reflection.AssemblyCompanyAttribute("CameraInterface")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+7b5b6f31f3c0f5392844872ebdfe54c4a1104f29")]
[assembly: System.Reflection.AssemblyProductAttribute("CameraInterface")]
[assembly: System.Reflection.AssemblyTitleAttribute("CameraInterface")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generated by the MSBuild WriteCodeFragment class.


//[assembly: XmlnsDefinition("EPIC.CameraInferface;assembly=CameraInferface", "CameraInferface")]

namespace EPIC.CameraInterface
{

    [AttributeUsage(AttributeTargets.Assembly)]
    public class RootNamespaceAttribute : Attribute
    {
        public string Namespace { get; }
        public RootNamespaceAttribute(string ns) => Namespace = ns;
    }
}

