//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: EPIC.DataLayer.RootNamespaceAttribute("EPIC.DataLayer")]
[assembly: System.Reflection.AssemblyCompanyAttribute("DataLayer")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+7b5b6f31f3c0f5392844872ebdfe54c4a1104f29")]
[assembly: System.Reflection.AssemblyProductAttribute("DataLayer")]
[assembly: System.Reflection.AssemblyTitleAttribute("DataLayer")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows8.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows8.0")]

// Generated by the MSBuild WriteCodeFragment class.


namespace EPIC.DataLayer
{

    [AttributeUsage(AttributeTargets.Assembly)]
    public class RootNamespaceAttribute : Attribute
    {
        public string Namespace { get; }
        public RootNamespaceAttribute(string ns) => Namespace = ns;
    }
}

